##docker run -p7474:7474 -p7687:7687 -e NEO4J_AUTH=neo4j/s3cr3t neo4j

version: "2"
services:
  neo4j:
    image: neo4j:4.2
    container_name: neo4j
    environment:
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
    volumes:
      - ./conf:/conf
      - ./graph:/data
      - ./logs:/logs
    restart: unless-stopped
    ports:
       - 7474:7474
       - 7687:7687